<?php
/**
 * File slide.phtml
 *
 * The slide starts with element <li>
 *  - the image <img src="/images/slider/slide3.jpg".....
 *  - the first title
 *
 * since: 27.11.2022
 * author: alexej@kisselev.de
 */
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->addTranslationFile('slide3', __DIR__);
?>
    <!-- SLIDE  -->
<li data-index="rs-399" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-rotate="0" data-saveperformance="off" data-title="Smooth Mask" data-description="">
    <!-- MAIN IMAGE -->
    <img src="/images/slider/slide3.jpg" alt="slide4" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
    <!-- LAYERS -->
    <!-- LAYER NR. 1 -->
    <!-- layer-2 -->
    <div class="tp-caption BigBold-Button rev-btn " id="slide-399-layer-1" data-x="140" data-hoffset="" data-y="center" data-voffset="40" data-width="['auto']" data-height="['auto']" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:300;e:Power1.easeInOut;"
         data-style_hover="cursor:pointer;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
         data-start="2000" data-splitin="none" data-splitout="none" data-actions='[{"event":"click","action":"jumptoslide","slide":"next","delay":""}]' data-responsive_offset="on" data-responsive="off" style="z-index: 5;  visibility: visible; opacity: 0; border:none;
 transform: matrix(-1, 1, -1, 0, 2, 1);
 ">
        <div class="background_box" style="width: auto">
            <h2 style="font-size:48px; font-weight:800;">
                <?= $this->translate('text1', 'slide3') ?>
            </h2>
            <h2 style="font-size:72px; font-weight:900;" class="goto_real">
                <?= $this->translate('text2', 'slide3') ?>
            </h2>
            <h2 style="font-size:48px; font-weight:800; margin-bottom:25px;">
                <?= $this->translate('text3', 'slide3') ?>
            </h2>
            <a href="booking.html" class="slide_anchor" style="padding: 15px 40px;">
                <?= $this->translate('button.text', 'slide3') ?>
            </a>
        </div>
    </div>
</li>