<?php
/**
 * File section-top.phtml
 *
 * since: 04.12.2022
 * author: alexej@kisselev.de
 */

$lang = $this->getLanguage();
$title = $this->title ?? '';
$key = $this->key ?? '';
?>
<div class="ds_wrapper portfolio_heading_section">
    <div class="container">
        <div class="row">
            <!--  heading -->
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="pagecontent">
                    <div class="ds_pagecontentContent_title">
                        <h1>
                            <?= $title ?>
                        </h1>
                    </div>
                    <div class="ds_pagecontentContent_breadcrumb">
                        <p>
                            <a href="<?= $this->url('home', ['language' => $lang, 'action' => 'index']) ?>">
                                <?= $this->translate('nav.home') ?>
                            </a>
                            <?php if ($key === 'post'): ?>
                                &laquo;
                                <a href="<?= $this->url('home', ['language' => $lang, 'action' => 'blog']) ?>">
                                    <?= $this->translate('nav.blog') ?>
                                </a>
                            <?php endif; ?>
                            <?php if ($key === 'item'): ?>
                                &laquo;
                                <a href="<?= $this->url('home', ['language' => $lang, 'action' => 'gallery']) ?>">
                                    <?= $this->translate('nav.gallery') ?>
                                </a>
                            <?php endif; ?>
                            &laquo;
                            <span>
                                <?= $title ?>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
            <!--  heading -->
        </div>
    </div>
</div>
