<?php
/**
 * File slide.phtml
 *
 * The slide starts with element <li>
 *  - the image <img src="/images/slider/slide1.jpg".....
 *  - the first title
 *
 * since: 27.11.2022
 * author: alexej@kisselev.de
 */
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->addTranslationFile('slide1', __DIR__);
?>
    <!-- SLIDE  -->
    <li data-index="rs-397" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-rotate="0" data-saveperformance="off" data-title="Slide Mask" data-description="">
                            <!-- MAIN IMAGE -->
                            <img src="/images/slider/slide1.jpg" alt="slide1" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
                            <!-- LAYER NR. 1 -->
                            <div class="main_layer">
                                <h1 class="tp-caption NotGeneric-Title playfont  tp-resizeme" id="slide-397-layer-1" data-x="140" data-hoffset="" data-y="center" data-voffset="-110" data-width="['auto','auto','auto','auto']"
                                    data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;"
                                    data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                                    data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 8; white-space: nowrap; font-size:60px; border-bottom:3px solid #538167; line-height: 70px; ">
                                    <?= $this->translate('text1', 'slide1') ?>
                                </h1>
                                <!-- LAYER NR. 2 -->
                                <h3 class="tp-caption NotGeneric-Title playfontbold  tp-resizeme" id="slide-397-layer-2" data-x="140" data-hoffset="" data-y="center" data-voffset="-12" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;"
                                    data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                                    data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; white-space: nowrap;  line-height: 50px;
margin:10px 0px;  padding-bottom:10px;  transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);">
                                <?= $this->translate('text2', 'slide1') ?>
</h3>
                                <!-- LAYER NR. 3 -->
                                <h4 class="tp-caption NotGeneric-Title  beard_s  tp-resizeme" id="slide-397-layer-3" data-x="140" data-hoffset="" data-y="center" data-voffset="100" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;"
                                    data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:[100%];s:inherit;e:inherit;"
                                    data-start="1200" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="z-index: 5; white-space: nowrap; font-size:104px; font-weight:500">
    <?= $this->translate('text3', 'slide1') ?>
                                </h4>
                                <!-- LAYER NR. 4 -->
                                <div class="tp-caption BigBold-Button rev-btn slider-anchor " id="slide-397-layer-4" data-x="140" data-hoffset="" data-y="bottom" data-voffset="80" data-width="['auto']" data-height="['auto']" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:300;e:Power1.easeInOut;"
                                     data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(41, 46, 49, 0);bc:rgba(255, 255, 255, 1.00);cursor:pointer;" data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
                                     data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-start="2000" data-splitin="none" data-splitout="none" data-actions='[{"event":"click","action":"jumptoslide","slide":"next","delay":""}]'
                                     data-responsive_offset="on" data-responsive="off" style="z-index: 9; white-space: nowrap; border:none; padding-left:0px;">
                                    <div>
                                        <a href="booking.html" class="slide_anchor anchor_d" style="padding:15px 40px;">
    <?= $this->translate('button.text', 'slide1') ?>
</a>
                                    </div>
                                </div>
                            </div>
                        </li>

