<?php
/**
 * File slide.phtml
 *
 * The slide starts with element <li>
 *  - the image <img src="/images/slider/slide4.jpg".....
 *  - the first title
 *
 * since: 27.11.2022
 * author: alexej@kisselev.de
 */
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->addTranslationFile('slide4', __DIR__);
?>
<li data-index="rs-400" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-rotate="0" data-fsmasterspeed="1500" data-fsslotamount="7"
    data-saveperformance="off" data-title="Letters Fly In"
    data-description="">
    <!-- MAIN IMAGE -->
    <img src="/images/slider/slide4.jpg" alt="slide1" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
    <!-- LAYERS -->
    <!-- LAYER NR. 1 -->
    <!-- LAYER NR. 2 -->
</li>