<?php
/**
 * File layout.phtml
 *
 * since: 26.11.2022
 * author: alexej@kisselev.de
 */

$this->addTranslationFile('layout', __DIR__);

/* current language like de, en etc. */
$currentLanguage = $this->getServiceManager()->get('translator')->getLocale();
?>
<!--[if IE 9]>
<html lang="<?= $currentLanguage ?>" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="<?= $currentLanguage ?>">
<!--<![endif]-->
<!-- Header Start -->

<head>
    <meta charset="UTF-8">
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headTitle(
        $this->translate('meta.title', 'layout'))
        ->setSeparator(' - ')
        ->setAutoEscape(false) ?>
    <!--Main Css Start-->
    <link rel="stylesheet" href="/css/main.css">
    <!--Main Css End-->
    <!--color changing css file-->
<!--    <link rel="stylesheet" id="theme-change" type="text/css" href="/css/color4.css">-->
    <!--color changing css file end-->
    <!--custom css file -->
    <link rel="stylesheet" id="theme-change" type="text/css" href="/css/override.css">
    <!--custom css file end -->
    <!-- favicon-icon -->
    <link rel="icon" type="image/png" href="/images/favicon-icon.png">

    <!-- favicon-icon -->
</head>
<!-- Header End -->

<!-- Body Start -->
<body>

<?= $this->render('section/header/header') ?>

<?= $this->content ?>

<?= $this->render('section/footer/footer') ?>
<!-- footer end -->

<!-- bottom tab -->
<!-- <div class="accordion">
    <h3>Part 1</h3>
    <h3>Sub-Div1</h3>
    <div>
    <p>This is a sub-div</p>
    </div>
    <h3>Part 2</h3>
    <div>
    <p>This is part 2</p>
    </div>
    </div> -->
<!-- Bootstrap script -->
<script src="/js/jquery.min.js">
</script>
<script src="/js/bootstrap.min.js">
</script>
<script type="text/javascript" src="/js/scripts.js">
</script>
<!-- script -->
<!-- bx slider script -->
<script type="text/javascript" src="/js/plugins/bxcrousel/js/jquery-bxslider.js">
</script>
<!-- bx slider script end -->
<!-- REVOLUTION JS FILES -->
<script type="text/javascript" src="/js/plugins/revolution/js/jquery.themepunch.tools.min.js">
</script>
<script type="text/javascript" src="/js/plugins/revolution/js/jquery.themepunch.revolution.min.js">
</script>
<script type="text/javascript" src="/js/plugins/revolution/js/revolution.extension.layeranimation.min.js">
</script>
<script type="text/javascript" src="/js/plugins/revolution/js/revolution.extension.navigation.min.js">
</script>
<script type="text/javascript" src="/js/plugins/revolution/js/revolution.extension.slideanims.min.js">
</script>
<script type="text/javascript" src="/js/plugins/revolution/js/revolution.extension.actions.min.js">
</script>
<script type="text/javascript" src="/js/plugins/revolution/js/revolution.extension.parallax.min.js">
</script>
<!-- REVOLUTION JS FiLES -->
<!-- photo gallery -->
<script src="/js/plugins/photogallery/js/jquery.prettyPhoto.js" type="text/javascript">
</script>
<script src="/js/plugins/portfolio/js/jquery.mixitup.js" type="text/javascript">
</script>
<!-- photo gallery -->
<!-- ui tabs  -->
<script src="/js/plugins/uitabs/js/jquery-ui.js" type="text/javascript">
</script>
<!-- ui tabs  -->
<!--counter js-->
<script type="text/javascript" src="/js/plugins/counter/js/jquery.countTo.js">
</script>
<!--counter js-->
</body>
