<?php
/**
 * File slide.phtml
 *
 * The slide starts with element <li>
 *  - the image <img src="/images/slider/slide2.jpg".....
 *  - the first title
 *
 * since: 27.11.2022
 * author: alexej@kisselev.de
 */
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$this->addTranslationFile('slide2', __DIR__);
?>
    <!-- SLIDE  -->
<li data-index="rs-398" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-rotate="0" data-saveperformance="off" data-title="Smooth Mask" data-description="">
    <!-- MAIN IMAGE -->
    <img src="/images/slider/slide2.jpg" alt="slide2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
    <!-- LAYERS -->
    <!-- LAYER NR. 1 -->
    <div class="tp-caption NotGeneric-Title   tp-resizeme" id="slide-398-layer-1" data-x="700" data-hoffset="" data-y="center" data-voffset="-90" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;"
         data-transform_in="x:50px;opacity:0;s:1000;e:Power3.easeOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on"
         style="z-index: 8; white-space: nowrap; font-size: 30px; line-height: 30px;">
        <div class="background_box" style="width: auto">
            <h2 style="font-size:48px; font-weight:800;">
                <?= $this->translate('text1', 'slide2') ?>
            </h2>
            <h2 style="font-size:72px; font-weight:900;" class="goto_real">
                <?= $this->translate('text2', 'slide2') ?>
            </h2>
            <h2 style="font-size:48px; font-weight:800; margin-bottom:25px;">
                <?= $this->translate('text3', 'slide2') ?>
            </h2>
            <a href="booking.html" class="slide_anchor" style="padding: 15px 40px;">
                <?= $this->translate('button.text', 'slide2') ?>
            </a>
        </div>
    </div>
</li>
