<?php
/**
 * File item.phtml
 *
 * since: 27.11.2022
 * author: alexej@kisselev.de
 */


$this->addTranslationFile('item2', __DIR__);

// sidebar populate posts translations
$this->addTranslationFile('gallery', dirname(__DIR__) . '/gallery');

$lang = $this->getLanguage();
$galleryUrl = $this->url('home', ['language' => $lang, 'action' => 'gallery']);

echo $this->render('section/_default/top', [
    'title' => $this->translate('item.title', 'item2'),
    'key'   => 'item'
]);
?>


<div class="ds_wrapper  portfolio_slider_sec">
    <div class="container">
        <div class="row">
            <div class="content">
                <!-- category slider start-->
                <div class="col-sm-7 col-lg-7 col-md-7">
                    <div class="slider_main">
                        <ul class="slider_bx">
                            <li>
                                <img alt="portfolio" src="/images/item2/dummy_760x460.png" class="img-responsive"/>
                            </li>
                            <li>
                                <img alt="portfolio" src="/images/item2/dummy_760x460.png" class="img-responsive"/>
                            </li>
                            <li>
                                <img alt="portfolio" src="/images/item2/dummy_760x460.png" class="img-responsive"/>
                            </li>
                            <li>
                                <img alt="portfolio" src="/images/item2/dummy_760x460.png" class="img-responsive"/>
                            </li>
                            <li>
                                <img alt="portfolio" src="/images/item2/dummy_760x460.png" class="img-responsive"/>
                            </li>
                        </ul>
                    </div>
                </div>

                <!-- category slier end -->
                <!-- right side description -->
                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="ds_projectdescription full_width">
                        <div class="topLeftBlog">
                            <h2 class="title" style="margin-top: 0">
                                <?= $this->translate('item.title', 'item2') ?>
                            </h2>
                        </div>
                        <div class="ds_blogContent full_width">
                            <div class="ds_blog1content full_width">
                                <p>
                                    <?= $this->translate('item.text1', 'item2') ?>
                                </p>
                                <p>
                                    <?= $this->translate('item.text2', 'item2') ?>
                                </p>
                            </div>
                            <a class="blogmore" href="<?= $galleryUrl ?>">
                                &laquo; <?= $this->translate('button.back.title') ?>
                            </a>
                        </div>
                        <div class="clear">
                        </div>
                    </div>
                </div>
                <!-- right side description -->
            </div>
        </div>
    </div>
</div>

